name = "LearningMachine"
uuid = "634aa325-58bb-4433-8165-053721a5c3a4"
authors = ["Thierry Moudiki <thierry.moudiki@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
